server/src/main/java/com/exchangediary/diary/domain/entity/Diary.java
server/src/main/java/com/exchangediary/diary/domain/entity/UploadImage.java

> 한 줄 요약 - 피드백 반영
- 초기화 이후 변경 가능성 없는 엔티티 필드에 대해서 `final` 추가
- `final` 선언된 필드는 반드시 생성자에서 초기화되어야 하므로 기본생성자 어노테이션에 `force=true` 옵션 추가함. 
- `force=true` 옵션이란, 모든 `final` 필드를 그 타입의 기본값으로 초기화됨. ex) 0 / `false` / `null`
https://github.com/exchangeDiary2024/exchange-diary/blob/14955719876b445d6246b8b2378e3b45b3565ccf/server/src/main/java/com/exchangediary/diary/domain/entity/Diary.java#L27-L29
- 연관관계(일대일, 다대일)에 지연 로딩 옵션 추가
- closed #2

[back/feature] 일기, 업로드 이미지 엔티티에 final 타입 및 지연로딩 추가

---

server/src/main/java/com/exchangediary/global/service/StaticImageQueryService.java
server/src/main/java/com/exchangediary/global/ui/StaticImageController.java
server/src/main/java/com/exchangediary/global/ui/dto/response/MoodsResponse.java

> 기분 목록 조회 API를 개발했습니다
- 팩토리메서드 네이밍컨벤션 학습
- dto 생성
- 컨트롤러 생성
- 서비스 생성
- closed #39
예은님이 만들어주신 쿼리 사용해서 거의 유사한 형태로 작업했습니다.
지금 코드는 스티커 목록 조회와 완전히 동일한 출력을 하고 있어서 만들어주신 StaticImageResponse record를 사용했는데, 다음 mvp에서 그룹 기능이 추가되면 분리하게 될 것 같습니다.
[도움이 되었거나, 참고했던 사이트(코드링크)](https://ibnahmadmohamed.medium.com/design-patterns-factory-method-naming-conventions-5e843b1cdbaf)

기분 목록 조회 API 개발

---

server/src/main/java/com/exchangediary/global/service/ImageService.java

> 기분목록조회 및 스티커목록조회 imageUrl이 null로 나오는 문제를 해결했습니다.
- StaticImage 저장 과정에서 url 설정 이후 save를 하지 않아서 url이 null로 나오는 문제를 해결했습니다.
- UploadImage 저장 과정에서 url 설정 이후 save를 하지 않아서 url이 null로 나오는 문제를 해결했습니다.
- 모든 url을 상수로 리팩토링했습니다.
- 파일명 저장 로직을 변경했습니다 (/제거)
- closed #80
- 해결 전
- 해결 후
검수를 꼼꼼히 하겠습니다😨

기분목록조회 이미지url null로 나오는 문제 해결

---

server/src/main/java/com/exchangediary/diary/domain/entity/Sticker.java

> 한 줄 요약 : sticker 엔티티 오류 해결
- sticker 엔티티 `id` 네이밍이 `Id`로 되어있어서 컨벤션에 맞게 변경했습니다.
- sticker 엔티티를 생성하는 정적팩터리메서드 `of()`에 `rotation` 필드 값을 설정하는 부분이 누락되어 추가했습니다.
- closed #83
- 통합 테스트 코드
```java
@Test
void 스티커_붙이기_성공() {
StickerRequest stickerRequest = StickerRequest.builder()
.coordX(1.0)
.coordY(2.0)
.width(1.0)
.height(2.0)
.rotation(90.0)
.build();
var response = RestAssured
.given().log().all()
.contentType(ContentType.JSON)
.body(stickerRequest)
.when().post("/diary/" + 1 + "/sticker/" + 1)
.then().log().all()
.statusCode(HttpStatus.CREATED.value())
.extract();
String location = response.header("location");
assertThat(location).isEqualTo("/diary/" + 1);
// TODO: Location으로 API 요청 후, 스티커 붙여졌는지 확인
RestAssured
.given().log().all()
.when().get(location)
.then().log().all() …
```

sticker 엔티티 오류 해결

---

server/src/main/java/com/exchangediary/member/domain/entity/Member.java

> 한 줄 요약: 사용자 엔티티 그룹 관련 필드 추가
- 그룹 관련 필드를 사용자 엔티티에 추가
- 닉네임, 일기 작성 순서, 프로필 이미지 경로
- closed #124

사용자 엔티티 그룹 관련 필드 추가

---

server/src/main/java/com/exchangediary/diary/ui/dto/response/DiaryDetailResponse.java
server/src/main/java/com/exchangediary/global/util/DateTimeUtil.java

> 한 줄 요약: 일기 조회 API 날짜 형식 수정
- 디자인에 맞게 일기 조회 API 날짜 형식을 수정했습니다. 
- yyyy년 M월 dd일 ➡️ yyyy.M.dd
- closed #137

일기 조회 API 수정

---

server/src/main/java/com/exchangediary/global/exception/ErrorCode.java
server/src/main/java/com/exchangediary/global/exception/serviceexception/notfound/GroupNotFoundException.java
server/src/main/java/com/exchangediary/group/domain/GroupRepository.java
server/src/main/java/com/exchangediary/group/service/GroupCodeService.java
server/src/main/java/com/exchangediary/group/ui/ApiGroupController.java
server/src/main/java/com/exchangediary/group/ui/dto/request/GroupCodeRequest.java
server/src/main/java/com/exchangediary/group/ui/dto/response/GroupIdResponse.java
server/src/test/java/com/exchangediary/group/GroupCodeServiceTest.java
server/src/test/java/com/exchangediary/group/GroupCodeTest.java

> 한 줄 요약: 그룹 코드 유효성 검증 서비스 개발
> #107 이슈에 연결된 브렌치가 닫혀서 자동으로 #127 pr이 닫혀버려서 다시 pr 올립니다.
- 그룹 코드 유효성 검증을 구현했습니다.
- 그룹 코드 유효성 검증 실패 시, `GroupNotFoundException`을 던지도록 구현했습니다.
- 그룹 코드 유효성 검증 성공과 실패 경우에 대한 테스트를 작성하였습니다.
- 그룹 코드 유효성 검증과 관련된 API가 확정되어서 컨트롤러를 추가했습니다.
- 그에 따른 웹 서버 + 클라이언트 RestAssured를 사용한 통합 테스트도 작성했습니다.
- 추후 그룹 생성 API, 사용자 정보 수정 API가 구현 완료되면 주석으로 작성된 시나리오대로 테스트 수정해볼 예정입니다.
- closed #108
- closed #127 
많은 피드백 부탁드려용 🤗

그룹 코드 유효성 검증 API 개발

---

server/src/main/java/com/exchangediary/group/domain/entity/Group.java
server/src/main/java/com/exchangediary/group/service/GroupCommandService.java
server/src/main/java/com/exchangediary/group/ui/ApiGroupController.java
server/src/main/java/com/exchangediary/group/ui/dto/request/GroupNameRequest.java
server/src/main/java/com/exchangediary/group/ui/dto/response/GroupIdResponse.java
server/src/test/java/com/exchangediary/group/GroupCodeServiceTest.java
server/src/test/java/com/exchangediary/group/GroupCodeTest.java
server/src/test/java/com/exchangediary/group/GroupCommandServiceTest.java
server/src/test/java/com/exchangediary/group/GroupCreateTest.java

> 그룹 생성 API 개발
- 그룹 생성 API에 필요한 컨트롤러를 추가했습니다. 
- 구현되어있던 그룹 생성 서비스의 반환값을 dto로 수정했습니다. 
- 그룹 생성 성공 API에 대한 통합테스트를 구현했습니다. 
- closed #140 
- 서비스 레이어 반환 타입이 수정됨에 따라서 테스트가 동작하도록 수정하였습니다. 
모두 통과하는 것을 확인할 수 있습니다.
컨트롤러에 도메인이 노출되는 것을 피하기 위해서 서비스 레이어의 반환값을 dto로 수정하였습니다. 
이 부분에 대한 다른 의견이 있다면 나누어봤으면 좋겠어요!

그룹 생성 API 개발

---

server/src/main/java/com/exchangediary/diary/domain/entity/UploadImage.java

> 업로드 이미지 엔티티 수정
- 업로드 이미지 엔티티의 image 필드 타입을 수정했습니다. https://github.com/Buddies2024/spring/blob/f8b49d221387ee29ff27de67ea822bb7d4176893/server/src/main/java/com/exchangediary/diary/domain/entity/UploadImage.java#L35-L38
- 업로드 이미지 엔티티의 image 필드가 postgresql의 oid 타입으로 매핑되는데,
테스트 환경의 데이터베이스인 h2 데이터베이스가 oid 타입을 인지하지 못하는 문제를 발견했습니다. 
- 따라서 @JdbcType 어노테이션의 LONGVARBINARY 타입을 갖도록 추가해주었습니다. 
- 업로드 이미지 엔티티의 diary 필드에 not null 제약조건을 추가했습니다. 
https://github.com/Buddies2024/spring/blob/f8b49d221387ee29ff27de67ea822bb7d4176893/server/src/main/java/com/exchangediary/diary/domain/entity/UploadImage.java#L39-L42
- closed #164 
[Mybatis jdbctype(마이바티스 Jdbctype)](https://lts0606.tistory.com/615)

업로드 이미지 엔티티 수정

---

server/src/main/java/com/exchangediary/diary/domain/entity/UploadImage.java

> 업로드 이미지 엔티티 오류 해결
- 업로드 이미지 엔티티의 diary 필드의 not null 제약조건 제거
- 오류의 이유는 #170 참고
- closed #170
- 이렇게 또 한 번 테스트 코드의 중요성을 느낀다...
일기 부분에도 얼른 테스트 코드 추가해야할 듯!!!

업로드 이미지 엔티티 오류 해결

---

server/src/main/java/com/exchangediary/group/service/GroupCreateService.java
server/src/main/java/com/exchangediary/group/service/GroupJoinService.java
server/src/main/java/com/exchangediary/group/ui/ApiGroupController.java
server/src/main/java/com/exchangediary/group/ui/dto/request/GroupCreateRequest.java
server/src/main/java/com/exchangediary/group/ui/dto/request/GroupNameRequest.java
server/src/main/java/com/exchangediary/group/ui/dto/response/GroupCreateResponse.java
server/src/main/java/com/exchangediary/group/ui/dto/response/GroupIdResponse.java
server/src/main/java/com/exchangediary/member/domain/entity/Member.java
server/src/test/java/com/exchangediary/group/api/GroupCreateApiTest.java

> 그룹 생성 API 수정
- 그룹 생성 API를 수정했습니다. 
- 요청 시 그룹 정보(이름)과 사용자의 그룹 정보(닉네임, 프로필 이미지 경로)를 받습니다.
- 응답 시 생성된 그룹의 id와 코드가 반환됩니다.
- 테스트 수정 및 잘못된 요청에 대한 테스트를 추가했습니다.
- closed #193

그룹 생성 API 수정

---

server/src/main/java/com/exchangediary/group/service/GroupQueryService.java
server/src/test/java/com/exchangediary/group/api/GroupProfileApiTest.java

> 프로필 이미지 선택 조회 API 수정
- 프로필 이미지 선택 조회 API에서 그룹 인원 초과 에외를 처리했던 것을 제거했습니다.
- 그룹원이 7명인 경우의 테스트명을 수정하고, 그룹원이 없는 경우에 대한 테스트를 추가했습니다.
- closed #195

프로필 이미지 선택 조회 API 수정

---

src/main/java/com/exchangediary/group/service/GroupCreateService.java
src/main/java/com/exchangediary/group/service/GroupJoinService.java
src/main/java/com/exchangediary/member/domain/entity/Member.java
src/main/java/com/exchangediary/member/domain/enums/GroupRole.java
src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
src/test/java/com/exchangediary/diary/api/DiaryWritableStatusApiTest.java
src/test/java/com/exchangediary/group/api/GroupCreateApiTest.java
src/test/java/com/exchangediary/group/api/GroupJoinApiTest.java
src/test/java/com/exchangediary/group/api/GroupMembersOrderApiTest.java

> 그룹 역할 필드 추가
- 그룹 역할(GroupRole) enum을 생성했습니다.
```java
public enum GroupRole {
GROUP_LEADER, // 그룹장
GROUP_MEMBER  // 그룹원
}
```
- 멤버 엔티티에 그룹 역할 필드를 추가했습니다.
- 그룹 생성 시 사용자의 그룹 역할은 그룹장(`GROUP_LEADER`)이고, 
그룹 가입 시 사용자의 그룹 역할은 그룹원(`GROUP_MEMBER`)입니다.
- 그룹 생성, 가입 성공 테스트에서 그룹 역할 확인 검증을 추가했습니다.
- closed #237 
- closed #238

그룹 역할 필드 추가

---

src/main/java/com/exchangediary/diary/domain/DiaryRepository.java
src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
src/main/java/com/exchangediary/diary/ui/dto/response/DiaryWritableStatusResponse.java
src/test/java/com/exchangediary/diary/api/DiaryWritableStatusApiTest.java

> 일기 작성 상태 조회 api 수정 - 볼 수 있는 일기id 값 반환
- 볼 수 있는 일기에 대해 일기 id 값 반환 해줌
- closed #276 
- 케이스1에 해당하는 테스트 일기 id 반환값 확인, 내가 오늘 일기 작성한 경우 테스트 추가해주었습니다.

일기 작성 상태 조회 api 수정 - 볼 수 있는 일기id 값 반환

---

src/main/java/com/exchangediary/diary/domain/entity/Diary.java
src/main/java/com/exchangediary/diary/domain/entity/UploadImage.java
src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
src/main/java/com/exchangediary/diary/service/DiaryValidationService.java
src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
src/test/java/com/exchangediary/diary/domain/DiaryRepositoryUnitTest.java

> 일기 서비스 리팩터링
- 일기 관련 유효성 검사 메서드들을 하나의 서비스로 분리했습니다. `DiaryValidationService`
- 일기 작성하기 메서드의 코드 중복을 제거했습니다.
- 사진을 업로드하는 경우와 그렇지 않은 경우를 하나의 흐름으로 작동 가능하게끔 리팩터링했습니다.
- 한 번의 생성으로 가능한 작업들이 setter 메서드에 의해 값이 변경되고 있는 부분들을 수정했습니다.
- setter의 사용을 지양하고 생성자 호출 시 필드값들이 초기화되도록 해주었습니다.
- 따라서 UplaodImage와 Diary의 모든 필드(id 제외)에 final 타입을 추가했습니다. 
- closed #284

일기 서비스 리팩터링

---

src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
src/main/java/com/exchangediary/global/exception/ErrorCode.java
src/main/java/com/exchangediary/group/domain/entity/Group.java
src/main/java/com/exchangediary/group/service/GroupCreateService.java
src/main/java/com/exchangediary/group/service/GroupLeaderService.java
src/main/java/com/exchangediary/group/service/GroupValidationService.java
src/main/java/com/exchangediary/group/ui/ApiGroupLeaderController.java
src/test/java/com/exchangediary/group/api/GroupLeaderHandOverApiTest.java
src/test/java/com/exchangediary/group/api/GroupLeaderSkipOrderApiTest.java

> 일기 순서 넘기기 API 구현
- 일기 순서 넘기기 API를 구현했습니다.
- 하루에 한 번 넘게 실행되는지 확인하기 위해서 Group 엔티티에 lastSkipOrderDate 필드를 추가했습니다.
- 마지막으로 일기 건너뛰기 권한을 실행한 날짜를 의미합니다.
- 성공, 실패의 경우에 대해 각각 테스트를 추가했습니다.
- 추후 방장 권한 인가 기능이 생기면 해당 테스트도 추가하도록 하겠습니다. 
- closed #239
- 일기 건너뛰기이지만 `skip order`을 사용한 이유는,
엄밀히 말하면 일기 순서를 건너뛰는(넘기는) 기능을 하는 API로 현재 저희 서비스 내에서 `order` 이라는 단어가 그룹 내 순서, 일기 작성 순서를 의미하고 있기 때문입니다.

일기 순서 넘기기 API 구현

---

src/main/java/com/exchangediary/group/domain/entity/Group.java
src/main/java/com/exchangediary/group/service/GroupCreateService.java
src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
src/test/java/com/exchangediary/diary/api/DiaryFindIdApiTest.java
src/test/java/com/exchangediary/diary/api/DiaryViewMonthlyTest.java
src/test/java/com/exchangediary/diary/api/DiaryWritableStatusApiTest.java
src/test/java/com/exchangediary/diary/service/DiaryQueryServiceTest.java
src/test/java/com/exchangediary/group/api/GroupCodeApiTest.java
src/test/java/com/exchangediary/group/api/GroupJoinApiTest.java
src/test/java/com/exchangediary/group/api/GroupLeaderHandOverApiTest.java
src/test/java/com/exchangediary/group/api/GroupLeaderSkipOrderApiTest.java
src/test/java/com/exchangediary/group/api/GroupMembersOrderApiTest.java
src/test/java/com/exchangediary/group/api/GroupNicknameApiTest.java
src/test/java/com/exchangediary/group/api/GroupProfileApiTest.java
src/test/java/com/exchangediary/group/service/GroupCodeServiceTest.java
src/test/java/com/exchangediary/member/domain/MemberRepositoryUnitTest.java

> 테스트에서 발생하는 not null 제약조건 오류 해결
- Group의 not null 제약조건이 걸린 lastSkipOrderDate 필드 값을 설정하지 않아서 오류가 발생했습니다.
- 따라서 그룹 생성 시 사용되는 정적팩터리메서드 of() 메서드에서 lastSkipOrderDate을 그룹 생성 전날로 설정해주었습니다.
- 또한 모든 테스트에서 그룹 생성 시 lastSkipOrderDate 값을 설정해주었습니다.
- closed #287

테스트에서 발생하는 not null 제약조건 오류 해결

---

src/main/java/com/exchangediary/diary/service/DiaryAuthorizationService.java
src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
src/main/java/com/exchangediary/diary/service/DiaryWriteService.java
src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
src/main/java/com/exchangediary/global/config/web/WebConfig.java
src/main/java/com/exchangediary/global/config/web/interceptor/WriteDiaryAuthorizationInterceptor.java
src/main/java/com/exchangediary/group/domain/GroupRepository.java
src/main/java/com/exchangediary/group/service/GroupQueryService.java
src/test/java/com/exchangediary/global/config/interceptor/WriteDiaryAuthorizationInterceptorTest.java
src/test/java/com/exchangediary/group/domain/GroupRepositoryUnitTest.java

일기 작성 인가 인터셉터 구현
<br>
- 일기 작성 인가 인터셉터를 구현했습니다.
> 일기 작성은 언제 허가되는가?
> 1. 사용자 그룹 순서가 그룹 순서와 일치
>  2. 오늘 작성된 일기가 없음.
- `DiaryAuthorizationService`을 만들어서 위 두 조건을 확인해주었습니다.
- 일기 인가가 필요한 url(`/group/{groupId}/diary`, `/api/groups/{groupId}/diaries`) 요청 시 
위 인터셉터를 거치도록 config에 추가했습니다.
- 일기 인가 인터셉터 테스트를 작성했습니다.
- closed #253

일기 작성 인가 인터셉터 구현

---

src/main/java/com/exchangediary/group/service/GroupLeaderService.java
src/main/java/com/exchangediary/group/service/GroupMemberService.java
src/main/java/com/exchangediary/group/ui/dto/request/GroupLeaderHandOverRequest.java
src/test/java/com/exchangediary/group/api/GroupLeaderHandOverApiTest.java

> 방장 권한 넘기기 API 수정
- 닉네임 요청받도록 수정
- `AS-IS` : 방장 권한을 넘길 사용자의 그룹 내 인덱스
- `TO-BE` : 방장 권한을 넘길 사용자의 닉네임 (그룹 내 유니크한 값)
- closed #297

방장 권한 넘기기 API 수정

---

src/main/java/com/exchangediary/diary/domain/DiaryRepository.java
src/main/java/com/exchangediary/diary/service/DiaryAuthorizationService.java
src/main/java/com/exchangediary/diary/service/DiaryWriteService.java
src/main/java/com/exchangediary/global/config/web/WebConfig.java
src/main/java/com/exchangediary/global/config/web/interceptor/ViewDiaryAuthorizationInterceptor.java
src/main/java/com/exchangediary/global/exception/ErrorCode.java
src/main/java/com/exchangediary/group/service/GroupCreateService.java
src/main/java/com/exchangediary/group/service/GroupJoinService.java
src/main/java/com/exchangediary/member/domain/entity/Member.java
src/main/java/com/exchangediary/member/service/MemberRegistrationService.java
src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
src/test/java/com/exchangediary/diary/api/DiaryWritableStatusApiTest.java
src/test/java/com/exchangediary/diary/api/DiaryWriteApiTest.java
src/test/java/com/exchangediary/diary/domain/DiaryRepositoryUnitTest.java
src/test/java/com/exchangediary/global/config/interceptor/ViewDiaryAuthorizationInterceptorTest.java
src/test/java/com/exchangediary/global/config/interceptor/WriteDiaryAuthorizationInterceptorTest.java
src/test/java/com/exchangediary/group/api/GroupLeaderHandOverApiTest.java
src/test/java/com/exchangediary/group/api/GroupLeaderSkipOrderApiTest.java
src/test/java/com/exchangediary/group/api/GroupMembersOrderApiTest.java
src/test/java/com/exchangediary/group/domain/GroupRepositoryUnitTest.java

> 일기 조회 인가 구현
- 일기 조회를 위해서 멤버 엔티티에 조회 가능한 마지막 일기 날짜(`lastViewableDiaryDate`) 필드를 추가했습니다.
- 새로운 일기 추가 시, 일기 작성자와 그 다음 일기 작성자의 `lastViewableDiaryDate` 필드가 일기 작성일자로 업데이트됩니다.
- 일기 조회 인가 인터셉터를 구현했습니다.
- webConfig에 일기 조회 url(`/group/{groupId}/diary`)에 일기 조회 인가 인터셉터를 거치도록 추가했습니다.
- 일기 조회 인가 인터셉터 테스트를 추가했습니다.
- closed #254

일기 조회 인가 구현

---

src/main/java/com/exchangediary/group/service/GroupMemberService.java
src/main/java/com/exchangediary/group/service/GroupQueryService.java
src/test/java/com/exchangediary/group/api/GroupMembersOrderApiTest.java

> 그룹원 정보 조회 API 수정
- 현재 일기 작성자를 현재 그룹 순서와 일치하는 사용자로 변경했습니다.
- 이유는 이슈 코멘트 참고
- closed #303

그룹원 정보 조회 API 수정

---

src/main/java/com/exchangediary/group/service/GroupLeaderService.java
src/main/java/com/exchangediary/group/service/GroupMemberService.java
src/test/java/com/exchangediary/group/api/GroupLeaderSkipOrderApiTest.java

> 일기 건너뛰기 API 오류 해결
- 일기 건너뛰기 시, 
순서 넘겨받은 사용자의 조회 가능한 마지막 일기 날짜(`lastViewableDiaryDate`) 필드가 업데이트되지 않는 오류가 있어 해결했습니다.
- closed #306

일기 건너뛰기 API 오류 해결

---

.gitignore
build.gradle
src/main/java/com/exchangediary/global/exception/GlobalExceptionHandler.java
src/main/resources/console-appender.xml
src/main/resources/file-error-appender.xml
src/main/resources/file-info-appender.xml
src/main/resources/jdbc-appender.xml
src/main/resources/jdbc-loggers.xml
src/main/resources/log4jdbc.log4j2.properties
src/main/resources/logback-spring.xml

> 백엔드 에러 로깅 추가
- `logback`와 `log4j2` 중 `logback` 라이브러리를 선택했습니다.
- `log4j2` 라이브러리는 비동기 로깅, Loom 백그라운드 로깅을 지원하고, `logback`보다 성능이 좋다고 알고 있지만
저희 서비스에서 위와 같은 기능을 지원하는 로깅까지 필요없다고 판단하여 `logback` 라이브러리를 선택했습니다.
- `log4jdbc` 의존성과 `log4jdbc.log4j2.properties` 설정파일을 추가하여, 
실제 sql 쿼리문 로그를 볼 수 있도록 하였습니다.
- 로컬, 개발서버, 실제서버에 따라서 다른 로그를 출력할 수 있도록 설정했습니다.
- `local`은 콘솔에 sql query와 info 이상 레벨의 로그를 출력합니다.
- `dev`(개발 서버)는 info 파일에 sql query와 info 이상 레벨의 로그를 출력합니다.
- `prod`(배포 서버)는 info 파일에 info 이상의 레벨 로그를 출력하고, error 파일에 error 이상의 레벨 로그를 출력합니다.
- closed #337 
- 현재 서버가 어떤 환경의 서버인지를 구분하기 위해서 application.properties 파일에 아래 설정 추가 부탁드려요!!
```text
spring.profiles.active=local #dev, prod
```
- API 예외가 발생한 경우에 대해서 error 레벨의 로그가 발생하도록 설정해놓았습니다.
예외 클래스, 예외 메시지, 예외 발생 이유/값(value)가 나타날 수 있도록 아래와 같이 메시지를 설정해놓았는데, 어떤지 의견 …

백엔드 에러 로깅 추가

---

src/main/java/com/exchangediary/diary/service/DiaryWriteService.java
src/main/java/com/exchangediary/group/service/GroupLeaderService.java
src/main/java/com/exchangediary/group/service/GroupLeaveService.java
src/main/java/com/exchangediary/member/domain/entity/Member.java
src/test/java/com/exchangediary/diary/api/DiaryViewMonthlyTest.java
src/test/java/com/exchangediary/diary/api/DiaryWriteApiTest.java
src/test/java/com/exchangediary/global/config/interceptor/ViewDiaryAuthorizationInterceptorTest.java
src/test/java/com/exchangediary/group/api/GroupCreateApiTest.java
src/test/java/com/exchangediary/group/api/GroupJoinApiTest.java
src/test/java/com/exchangediary/group/api/GroupLeaveApiTest.java

> 그룹 탈퇴 시, 조회 가능한 마지막 일기 날짜 업데이트 오류 해결
- 그룹 탈퇴/강퇴 시, 현재 순서가 다른 그룹원으로 바뀔 경우, lastViewableDiaryDate를 업데이트했습니다.
- 조회 가능한 마지막 일기 날짜 업데이트 검증이 필요한 부분에 테스트를 추가했습니다.
- closed #345

그룹 탈퇴 시, 조회 가능한 마지막 일기 날짜 업데이트 오류 해결

---

src/main/java/com/exchangediary/diary/domain/DiaryRepository.java
src/main/java/com/exchangediary/diary/domain/dto/DiaryDay.java
src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
src/main/java/com/exchangediary/diary/ui/dto/response/DiaryDayResponse.java
src/main/java/com/exchangediary/diary/ui/dto/response/DiaryMonthlyResponse.java
src/main/java/com/exchangediary/member/service/MemberQueryService.java
src/test/java/com/exchangediary/diary/api/DiaryViewMonthlyTest.java

> 월별형 API 수정
- 일기 조회하기 api 가 생겨남에 따라 월별형 조회 api 에 일기 id 를 반환해주기로 결정
- closed #353

월별형 API 수정

---

src/main/resources/static/js/diary/write-page/check-textarea.js

> 일기 작성 페이지 엔터 및 백스페이스 기능 개선
- 페이지의 마지막 줄 마지막 글자에서 엔터할 경우에만 다음 페이지로 넘어감
- 첫번째 줄이 개행일때 백스페이스 누르면 개행이 삭제됨
- closed #396 
일기를 작성하며 불편한점이 있거나 개선했으면 하는 부분이 있다면 자유롭게 피드백 달아주세요~

일기 작성 페이지 엔터 및 백스페이스 기능 개선

---

src/main/java/com/exchangediary/group/service/GroupLeaderService.java
src/main/java/com/exchangediary/group/ui/ApiGroupController.java
src/main/java/com/exchangediary/group/ui/ApiGroupLeaderController.java
src/main/java/com/exchangediary/notification/component/FCMControllerAdvice.java
src/main/java/com/exchangediary/notification/component/FCMInitializer.java
src/main/java/com/exchangediary/notification/component/NotificationScheduler.java
src/main/java/com/exchangediary/notification/domain/NotificationRepository.java
src/main/java/com/exchangediary/notification/domain/entity/Notification.java
src/main/java/com/exchangediary/notification/service/MessageSendService.java
src/main/java/com/exchangediary/notification/service/NotificationService.java
src/main/java/com/exchangediary/notification/service/NotificationTokenService.java
src/main/resources/db/migration/V2.8__delete_unique_index_on_notification_member_id.sql
src/test/java/com/exchangediary/notification/api/NotificationApiTest.java
src/test/java/com/exchangediary/notification/domain/NotificationRepositoryUnitTest.java

> 사용자 - 알림 연관관계 변경 및 fcm 토큰 신선도 관리
- Member - Notifcation 엔티티의 연관관계를 일대다로 변경했습니다.
- 사용자가 여러 장치에 대해 fcm 토큰을 가질 수 있기 때문
- fcm 토큰 신선도 관리를 위해 생성된 지 한 달이 된 토큰은 삭제하도록 구현했습니다.
- 알림, 알림 토큰 서비스에서 다른 메서드를 사용하여 구현 가능한 알림들을 리팩터링했습니다.
- 일기 건너뛰기 알림
- 그룹원 가입 알림 
- closed #393
[FCM 등록 토큰 관리를 위한 권장사항](https://firebase.google.com/docs/cloud-messaging/manage-tokens?hl=ko)
[PostgreSQL DATEDIFF Function](https://www.geeksforgeeks.org/postgresql-datediff-function/)

사용자 - 알림 연관관계 변경 및 fcm 토큰 신선도 관리

---

src/main/resources/db/migration/V2.10__alter_diary_content_content.sql

> diary content 테이블 content 열 길이 늘리기
- 기존 diary content 테이블의 content 열 길이가 너무 작아 발생한 문제.
- VARCHAR이기 때문에 LONG VARCHAR 길이로 조정해줌
- closed #415
- hotfix이므로 머지 후 바로 서버 재배포 하도록 하겠습니다!

diary content 테이블 content 열 길이 늘리기

---

src/main/java/com/exchangediary/diary/domain/DiaryRepository.java
src/main/java/com/exchangediary/diary/service/DiaryDeleteService.java
src/main/java/com/exchangediary/diary/service/DiaryWriteService.java
src/main/java/com/exchangediary/diary/service/ImageService.java
src/main/java/com/exchangediary/group/service/GroupLeaveService.java
src/main/java/com/exchangediary/notification/service/NotificationTokenService.java
src/main/resources/db/migration/V3.2__add_unique_index_on_token.sql

> 일기 삭제 시 이미지 파일 삭제 및 fcm 토큰 유니크 제약조건 추가
- 일기가 삭제되어도 이미지 파일은 남아있어 불필요하게 메모리를 차지했습니다. 
따라서 일기 삭제 시 이미지 파일도 함께 삭제해주었습니다.
- fcm 토큰에 유니크 제약조건을 추가하여, 중복되는 fcm 토큰 레코드가 DB에 쌓이지 않도록 했습니다.
- closed #414

일기 삭제 시 이미지 파일 삭제 및 fcm 토큰 유니크 제약조건 추가

---

src/main/resources/static/js/group/monthly/draw-bottom.js
src/main/resources/static/js/group/monthly/draw-monthly.js

> 한 줄 요약
- 원인) 초기 바텀시트 그릴 때 한 번만 처리해서 발생하는 
- 해결) 바텀시트 그릴 때, 오늘 날짜 클릭 가능한 지 값 저장 후, 달력 그릴때마다 오늘 날짜 클릭 비활성화되도록하여 문제 해결
- closed #447
https://github.com/user-attachments/assets/b3a1b9dd-537e-47de-817b-9a9964fc4782
왕오랜만의 pr ~ 다시 달려봅시다!!! 화이팅 👏

일기 작성 권한 없는 경우 오늘 날짜 클릭되는 오류 해결

---

src/main/java/com/exchangediary/global/config/web/WebConfig.java
src/main/java/com/exchangediary/global/config/web/interceptor/JwtAuthenticationInterceptor.java
src/main/java/com/exchangediary/member/service/AnonymousService.java
src/main/java/com/exchangediary/member/service/CookieService.java
src/main/java/com/exchangediary/member/service/JwtService.java
src/main/java/com/exchangediary/member/service/MemberRegistrationService.java
src/main/java/com/exchangediary/member/ui/ApiAnonymousController.java
src/main/java/com/exchangediary/member/ui/KakaoLoginController.java
src/main/java/com/exchangediary/member/ui/dto/response/AnonymousInfoResponse.java
src/test/java/com/exchangediary/member/api/AnonymousApiTest.java
src/test/java/com/exchangediary/member/service/ExpiredJwtTest.java
src/test/java/com/exchangediary/member/service/JwtServiceTest.java
src/test/java/com/exchangediary/member/service/ReissueJwtTokenTest.java

> 익명의 사용자 정보 조회 API 구현
- 로그인 여부와 그룹 가입 여부를 알려주는 익명 사용자 정보 조회 API를 구현했습니다.
- 모든 경우(4가지)에 대해서 테스트를 작성했습니다.
- 로그인 여부 판별에 사용되는 jwt service와 cookie service를 리팩터링했습니다.
- closed #456
- 구현한 API 테스트 결과입니다.
- 현재 인터셉터 부분에서 실패하는 테스트가 있는데, #462에서 인터셉터 코드가 다량 변경되었기에 해당 pr 닫힌 후 머지하여 테스트 수정하도록 하겠습니다. 그러니까 얼른 pr 확인 부탁드려요~
- 작성된 [API 명세서](https://www.notion.so/yeeuniii/190d836989fc80f88de9e89b261fa559?pvs=4)에 맞게 구현되었는지 더블체크 부탁드려요!

익명의 사용자 정보 조회 API 구현

---

src/main/java/com/exchangediary/comment/service/CommentCreateService.java
src/main/java/com/exchangediary/comment/ui/ApiCommentController.java

> 댓글/답글 알림 구현
- 댓글 및 답글 작성 시 알림 구현했습니다.
- 기존에 구현해둔 notificationService의 pushNotification 메서드를 재사용했습니다.
- closed #371
직접 댓글 및 답글을 작성하면서 알림 테스트해보았습니다.
- 추후 모든 알림 메시지 수정 예정입니다. 또한 알림 목록 [노션](https://www.notion.so/glory-banana-f15/43253cc96545440c962dd1d59a338b80?pvs=4)에 정리했습니다.
- pushNotification 메서드를 재사용하고싶어 일기 작성자와 댓글 작성자를 조회하는 부분에서 불필요하게 데이터베이스를 조회하고 있습니다. 이 부분은 member 데이터베이스 구조 변경 후, 다시 고민해 볼 예정입니다.

댓글/답글 알림 구현

---

src/main/java/com/exchangediary/global/config/web/WebConfig.java
src/main/java/com/exchangediary/global/config/web/interceptor/JwtAuthenticationInterceptor.java
src/main/java/com/exchangediary/member/service/JwtService.java
src/main/java/com/exchangediary/member/ui/ApiKakaoLoginController.java
src/main/resources/application.properties

> 익명 조회 API 오류 해결
- jwt 토큰의 예외 처리가 제대로 되어 있지 않아서 access token이 만료 시 익명 조회 API에서 오류가 발생하여 403 페이지가 뜨는 오류가 있었습니다.
- jwt 서비스 내에서 예외 처리를 추가하여 문제를 해결했습니다.
- 오류를 해결하면서 /login 페이지에 대해서 인터셉터 처리가 정상적으로 되고 있지 않아서 함께 해결해주었습니다.
- 로그인한 사용자가 /login 페이지 접근 시 시작 페이지로 리다이렉트
- closed #477 
승인되면 머지 후, 재배포 진행하도록 하겠습니다!
hotfix이므로 가급적 빠른 확인 부탁드려요!!

익명 조회 API 오류 해결

---

src/main/java/com/exchangediary/global/config/web/interceptor/JwtAuthenticationInterceptor.java
src/main/java/com/exchangediary/member/service/AnonymousService.java
src/main/java/com/exchangediary/member/service/JwtService.java
src/main/java/com/exchangediary/notification/component/NotificationScheduler.java
src/main/java/com/exchangediary/notification/domain/NotificationRepository.java
src/main/java/com/exchangediary/notification/domain/entity/Notification.java
src/main/java/com/exchangediary/notification/service/NotificationTokenService.java
src/main/resources/application.properties
src/test/java/com/exchangediary/member/service/JwtServiceTest.java
src/test/java/com/exchangediary/member/service/ReissueJwtTokenTest.java
src/test/java/com/exchangediary/notification/api/NotificationApiTest.java
src/test/resources/application.properties

> 알림 오류 및 익명 정보 조회 API 오류 수정
- 익명 정보 조회 API 토큰 갱신이 잘못되는 부분 확인 후 수정하였습니다.
- jwtservice의 access token을 검증하는 함수에서 access token을 재발급하는 로직을 분리하여, token을 갱신하는 방식으로 수정해주었습니다.
- fcm 토큰 신선도 관리 sql문 오류 해결했습니다.
- sql에서 날짜를 비교하지 않고, java에서 연산 후 매개변수로 넘겨주어 날짜를 비교해주었습니다.
- 중복된 fcm token 저장 시도 시, unique 제약 조건으로 인해 DB에서 오류가 발생하였습니다.
예상할 수 있는 예외로 이 경우 DB에까지 요청이 전달되지 않도록 변경해주었습니다.
- 요청받은 토큰이 DB에 존재하는지 확인 후, 중복되지 않는 경우에만 DB에 저장해주었습니다.
- closed #482
익명 정보 조회 API에서 재발급된 access token 처리에서 계속 이슈가 발생하여서 이 부분 코드 제가 몇번 확인하였는데, 혹시 모르니 다같이 더블체크 한 번만 부탁드려요!!
[JPQL 로 시간 조건걸기](https://gist.github.com/jjangga0214/2dc6b788b8db74aadffb1625d6e7f6de)

알림 오류 및 익명 정보 조회 API 오류 수정

---

src/main/java/com/exchangediary/diary/service/DiaryWriteService.java
src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
src/main/java/com/exchangediary/diary/ui/dto/notification/DiaryWriteNotification.java
src/main/java/com/exchangediary/group/service/GroupCreateJoinService.java
src/main/java/com/exchangediary/group/service/GroupLeaderService.java
src/main/java/com/exchangediary/group/service/GroupLeaveService.java
src/main/java/com/exchangediary/group/ui/ApiGroupController.java
src/main/java/com/exchangediary/group/ui/ApiGroupLeaderController.java
src/main/java/com/exchangediary/group/ui/dto/notification/GroupJoinNotification.java
src/main/java/com/exchangediary/group/ui/dto/notification/GroupLeaderHandOverNotification.java
src/main/java/com/exchangediary/group/ui/dto/notification/GroupLeaderKickOutNotification.java
src/main/java/com/exchangediary/group/ui/dto/notification/GroupLeaderSkipDiaryNotification.java
src/main/java/com/exchangediary/group/ui/dto/notification/GroupLeaveNotification.java
src/main/java/com/exchangediary/member/domain/MemberRepository.java
src/main/java/com/exchangediary/member/domain/entity/Member.java
src/main/java/com/exchangediary/member/service/MemberQueryService.java
src/main/java/com/exchangediary/member/service/MemberUpdateService.java
src/main/java/com/exchangediary/member/ui/ApiMemberController.java
src/main/java/com/exchangediary/member/ui/dto/response/MemberNotificationResponse.java
src/main/java/com/exchangediary/notification/domain/NotificationRepository.java
src/main/java/com/exchangediary/notification/service/NotificationTokenService.java
src/main/resources/db/migration/V4.3__add_notifcation_on_column.sql
src/test/java/com/exchangediary/member/api/OnNotificationApiTest.java
src/test/java/com/exchangediary/notification/api/NotificationApiTest.java
src/test/java/com/exchangediary/notification/domain/NotificationRepositoryUnitTest.java

> 알림 활성화 속성 추가 및 API 구현
- 사용자 테이블에 boolean 타입의 알림 활성화 (`on_notification`) 속성 추가했습니다.
- fcm 토큰 조회 시, `on_notification`이 true인 사용자에 대해서만 조회합니다.
- API 명세서와 동일하게 [알림 활성화 여부 조회](https://www.notion.so/yeeuniii/1cfd836989fc80388fa4cdcac0f65d17?pvs=4)와 [알림 활성화 전환](https://www.notion.so/yeeuniii/1cfd836989fc804f9d90db95bc29cb79?pvs=4) API 구현 및 테스트 작성하였습니다.
- 조금 더 구체적인 내용을 전달할 수 있게끔 알림 메시지를 수정했습니다.
알림에 필요한 정보들을 요청 / 응답과 비슷하게 record 형식의 dto를 작성하여 서비스에서 컨트롤러로 전달했습니다.
- closed #491
- Notification 단위 테스트 / API 테스트 수정되었고, 추가된 알림 활성화 API 테스트 작성하였고, 그 결과입니다.
- 전체 테스트 코드 결과도 첨부합니다.
- 이번 v1.2에 포함되지 않는 댓글/답글에 대한 알림 메시지는 수정하지 않았습니다. v1.3 작업 시 수정하도록 하겠습니다.
- [알림 명세서](https://www.notion.so/yeeuniii/43253cc96545440c962dd1d59a338b80?pvs=4) 참고하여 메시지 수정하고 싶은 부분 있으면 말씀해주세요!!

알림 활성화 속성 추가 및 API 구현
