server/src/main/java/com/exchangediary/global/domain/entity/StaticImage.java
> StaticImage에 BaseEntity 상속
- closed #1
X
=> [back/chore] static image에 baseEntity 상속

client/.gitignore, client/src/global/navi/stackNavigator.tsx, client/src/global/navi/useStackNavigation.ts
> 한 줄 요약
useStackNavigation custom hook 추가
StackNavigator 추가
.gitignore DS_Store 추가
- closed #13
=> 13 frontfeature navigate 로직 추가

server/src/main/java/com/exchangediary/global/domain/entity/StaticImage.java
> 기존 StaticImage 엔티티를 피드백 받은 내용대로 수정했습니다.
- 생성 후 수정되지 않는 필드에 한해 final 키워드를 추가했습니다.
- import문에 와일드카드 사용한 부분을 제거하고 다시 import 했습니다.
- 인텔리제이 import 설정을 변경했습니다.
- closed #1
https://dev-kani.tistory.com/39
=> [back/feature] StaticImage entity final 수정 및 import 와일드카드 제거 

.github/workflows/deploy.yml
> 깃허브 액션과 ec2를 이용해서 자동 배포 스크립트를 작성했습니다.
- 깃허브 액션 환경변수 추가
- application.yml 추가 (환경변수 ver)
- 배포 스크립트 작성
- #24 
application.yml의 데이터베이스 환경변수로 수정
main 푸시 후 테스트 해봐야 할 것 같습니다. 진행상황 코멘트로 공유하겠습니다.
application.yml 환경변수
https://velog.io/@rhqjatn2398/Spring-Boot%EC%97%90%EC%84%9C-%ED%99%98%EA%B2%BD-%EB%B3%80%EC%88%98-%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0
깃허브 액션
https://velog.io/@songyuheon/GitHub-Action-EC2-%EB%B0%B0%ED%8F%AC
=> 서버 배포 스크립트 구축(임시)

server/src/main/resources/application.yml
> 배포를 위해서 환경변수로 수정한 application.yml 파일을 올립니다.
- application.yml 업로드
- closed #24
이전 PR 누락으로 다시 올립니다.
=> application.yml 환경변수 ver 업로드

server/src/main/resources/application.yml
> 배포 스크립트가 올바른 동작을 하는지 확인합니다.
- develop->main 브랜치 합병
- closed #24
=> 배포 스크립트 테스트

.github/workflows/deploy.yml
> 배포 테스트 중 깃허브 액션의 JD설정 누락으로 배포되지 않는 문제 발견하여 스크립트 수정
- JDK job 추가
- closed #24
=> 깃허브 가상환경 JDK 설정 추가

.github/workflows/deploy.yml
> 배포 스크립트에 누락되었던 JDK의 distribution을 추가했습니다.
- closed #24
=> 배포 스크립트 JDK job distribution 누락 해결

.github/workflows/deploy.yml
> 배포 스크립트가 동작하는지 테스트합니다.
- closed #24
=> 배포 스크립트 테스트 (JDK 문제 해결)

.github/workflows/deploy.yml
> 배포 스크립트 내 JDK job 깃허브 액션에서 지원되는 버전으로 수정
- closed #24
=> 배포 스크립트 jdk 지원되는 버전(temurin)으로 수정

.github/workflows/deploy.yml
> 깃허브 액션 환경변수 추가 및 스크립트 수정
- closed #24
=> 깃허브 액션 환경변수 등록

client/package.json, client/src/pages/editdiary/diaryScreen.js
> 텍스트 작성 영역과 편집기능 구현
- 텍스트 작성 영역 기능 구현
- 텍스트 편집 툴바 기능 구현
- close #45 
css 수정해야함
=> 일기작성 페이지 글작성영역 생성, 

.github/workflows/deploy.yml
> 기존 scp 명령어를 script에서 step으로 분리했습니다.
- closed #59
=> 깃허브 액션스 jar 복사 방식 수정

.github/workflows/deploy.yml
> 배포 스크립트의 공백 수정했습니다.
- closed #59
=> 배포 스크립트 공백 수정

.github/workflows/deploy.yml
> scp 다른 방식으로 수정
- closed #59
[도움이 되었거나, 참고했던 사이트(코드링크)](https://velog.io/@chlee4858/20211205-github%EC%97%90%EC%84%9C-CICD-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0-github-action)
=> 배포 스크립트 scp 다른 방식으로 시도

.github/workflows/deploy.yml
=> 배포 스크립스 수정 및 재배포

.github/workflows/deploy.yml
> 배포 스크립트 타임아웃 시간 설정
- closed #59
=> 배포 스크립트 수정

client/.gitignore, client/package-lock.json, client/package.json, client/src/pages/editdiary/components/imageModal.js, client/src/pages/editdiary/components/textModal.js, client/src/pages/editdiary/diaryScreen.js
이미지 삽입 구현 완료 및 텍스트 입력란 레이아웃 완료
텍스트 입력란 고정한 곳에 위치
텍스트 입력란 내에 이미지 첨부 기능 구현
css 변경
- closed #55
리뷰어에게 하고 싶은 말
도움이 되었거나, 참고했던 사이트(코드링크)
=> 이미지 삽입 구현 완료 및 텍스트 입력란 레이아웃 완료

server/src/main/java/com/exchangediary/global/config/web/interceptor/JwtAuthenticationInterceptor.java
> jwt 인증 인터셉터 수정
- request 속성에 member id가 아닌 member 넣기
- closed #168
=> jwt 인증 인터셉터 수정

server/src/main/resources/static/css/group/group-common.css, server/src/main/resources/templates/group-page.html
> 그룹 생성 및 가입 페이지 공통 부분 리팩터링
- 노트의 스프링 이미지도 단계마다 바뀌므로 step div에 넣기로 결정했습니다.
- closed #185 
https://github.com/Buddies2024/spring/blob/07e5200566df51d7cf300e73f3ba5a2ef76a72fb/server/src/main/resources/templates/group-page.html#L23-L32
- L23-24 부분의 step`#` 부분의 `#`에 본인이 구현하는 step 번호로 바꿔주세요.
- `subject` span에 각 단계의 제목을 기입하시면 됩니다. ex) `그룹코드를 입력해주세요.`
- `step-content` div는 제목부터 확인 위까지 크기를 갖도록 설정했습니다. 그 안에서 본인 단계에 해당하는 페이지 구현해주세요.
=> 그룹 생성 및 가입 페이지 공통 부분 리팩터링

server/src/main/resources/static/css/group/group-step3.css, server/src/main/resources/static/js/group/group-step3.js
>그룹 가입/생성 step3 구현
- closed #132
=> 그룹 가입/생성 step3 구현

server/src/main/resources/templates/base.html, server/src/main/resources/templates/diary/view-diary.html, server/src/main/resources/templates/diary/write-page.html, server/src/main/resources/templates/group-page.html, server/src/main/resources/templates/index.html, server/src/main/resources/templates/login.html
> 서버 배포시 타임리프에서 경로 찾지 못한 오류
- closed #220
=> 서버 배포시 타임리프에서 경로 찾지 못한 오류

server/src/main/java/com/exchangediary/diary/ui/DiaryController.java
> 다이어리 컨트롤러 반환 파일 경로 수정
- closed #223
=> 다이어리 컨트롤러 반환 파일 경로 수정

src/main/java/com/exchangediary/diary/ui/dto/response/DiaryMonthlyResponse.java, src/main/java/com/exchangediary/group/service/GroupCreateService.java, src/main/java/com/exchangediary/group/service/GroupJoinService.java, src/main/java/com/exchangediary/group/service/GroupValidationService.java, src/main/java/com/exchangediary/group/ui/dto/request/GroupCreateRequest.java, src/main/java/com/exchangediary/group/ui/dto/request/GroupJoinRequest.java, src/main/java/com/exchangediary/group/ui/dto/response/GroupMembersResponse.java, src/main/java/com/exchangediary/group/ui/dto/response/GroupProfileResponse.java, src/main/java/com/exchangediary/member/domain/entity/Member.java, src/test/java/com/exchangediary/group/api/GroupCreateApiTest.java, src/test/java/com/exchangediary/group/api/GroupJoinApiTest.java, src/test/java/com/exchangediary/group/api/GroupProfileApiTest.java, src/test/java/com/exchangediary/member/domain/MemberRepositoryUnitTest.java
> 캐릭터 이미지 저장방식 수정, 관련 api 수정
- profileLocation 저장하는 방식에서 profileImage 에 캐릭터 이름을 저장하는 형식으로 수정
- closed #234 
수정 후 모든 테스트 결과
=> 캐릭터 이미지 저장방식 수정, 관련 api 수정

src/main/java/com/exchangediary/diary/service/DiaryQueryService.java, src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java, src/main/java/com/exchangediary/diary/ui/dto/response/DiaryDayResponse.java, src/main/java/com/exchangediary/diary/ui/dto/response/DiaryMonthlyResponse.java, src/main/java/com/exchangediary/member/domain/MemberRepository.java, src/main/java/com/exchangediary/member/service/MemberQueryService.java, src/main/resources/static/js/group/monthly/draw-calendar.js, src/test/java/com/exchangediary/diary/api/DiaryViewMonthlyTest.java
> 달력형 조회 API 수정
- 작성된 일기에 대해서 조회 가능한지 판단하는 canView 데이터 추가
- closed #294
=> 달력형 조회 API 수정

src/main/resources/static/css/base.css, src/main/resources/static/css/confirm-modal.css, src/main/resources/static/css/diary/diary-common.css, src/main/resources/static/css/diary/modal.css, src/main/resources/static/css/diary/write-page.css, src/main/resources/static/css/group/group-common.css, src/main/resources/static/css/group/group-menu.css, src/main/resources/static/css/group/group-step1.css, src/main/resources/static/css/group/group-step2.css, src/main/resources/static/css/group/group-step3.css, src/main/resources/static/css/login.css, src/main/resources/static/css/notification-modal.css, src/main/resources/static/js/diary/write-page/write-diary.js, src/main/resources/static/js/group/group-menu.js, src/main/resources/templates/base.html
> 서버 배포를 하며 발생한 자잘한 프론트 버그 수정
- 테두리 끊김, 페이지 언어 한글로 변경, 화면 상단으로 올리기, 방장 탈퇴 불가 모달 추가
- closed #314 
리뷰어에게 하고 싶은 말
=> 서버 배포를 하며 발생한 자잘한 프론트 버그

src/main/resources/static/js/common/modal/confirm-modal.js, src/main/resources/static/js/group/group-menu.js, src/main/resources/static/js/group/leader.js
> 방장은 탈퇴 및 위임을 할 수 없음
- 방장 탈퇴 시 경고 메시지
- 방장 내보내기 시 경고 메시지
- 방장 위임 시 경고 메시지
- 방장 버튼 클릭시 나오는 confirmModal 에서 발생하던 버그 수정
- closed #338 
그룹원이 여러명인 경우 테스트를 해보지 못했습니다.
방장 넘기기, 방장이 그룹원 퇴출, 스스로 그룹 탈퇴 등 정상 작동 하는지 확인 부탁드립니다..!
=> 방장은 탈퇴 및 위임을 할 수 없음

src/main/resources/db/migration/V2.9__alter__member_group_foreign_key.sql
> 그룹 - 사용자 외래키 제약조건 수정
- 그룹 - 사용자 외래키 제약조건에서 on delete cascade 제거
- closed #398
=> 그룹 - 사용자 외래키 제약조건 수정

src/main/java/com/exchangediary/global/config/log/RequestLoggingConfig.java, src/test/java/com/exchangediary/diary/api/DiaryWriteApiTest.java
> 일기 작성 테스트 logFilter 오류 해결
- closed #401
=> 일기 작성 테스트 logFilter 오류 해결

src/main/resources/db/migration/V2.2__drop_upload_image.sql, src/main/resources/db/migration/V2.3__create_diary_content.sql
> 스키마 구조 쿼리 오류 해결
- v2.2 일기 image file name 속성값 설정 오류 해결
- v2.3 일기 content 긴 경우(255, 510 넘는 경우), diary content 생성
- closed #403
=> 스키마 구조 쿼리 오류 해결

src/main/resources/db/migration/V2.3__create_diary_content.sql
> 첫번째 페이지 생성 오류 해결
- 스키마 구조 첫번째 페이지 생성 명령어 오류 해결
=> 첫번째 페이지 생성 오류 해결

src/main/resources/templates/base.html
> GA 스크립트 수정
- GA 스크립트 수정
- closed #429
=> GA 스크립트 수정

src/main/java/com/exchangediary/comment/domain/CommentRepository.java, src/main/java/com/exchangediary/comment/service/CommentAuthorizationService.java, src/main/java/com/exchangediary/comment/service/CommentQueryService.java, src/main/java/com/exchangediary/comment/ui/ApiCommentController.java, src/main/java/com/exchangediary/comment/ui/dto/response/CommentCreationVerifyResponse.java, src/test/java/com/exchangediary/comment/api/CommentCreationVerifyApiTest.java
> 댓글창 생성 유효성 검증 API
- 댓글창 생성 가능한 상태인지 검사
- 자신의 프로필 이미지 반환
- closed #368
=> 댓글창 생성 유효성 검증 API

src/main/java/com/exchangediary/comment/service/CommentQueryService.java, src/main/java/com/exchangediary/comment/ui/ApiCommentController.java, src/main/java/com/exchangediary/comment/ui/dto/response/CommentResponse.java, src/main/java/com/exchangediary/comment/ui/dto/response/ReplyResponse.java, src/test/java/com/exchangediary/comment/api/CommentViewApiTest.java, src/test/java/com/exchangediary/comment/api/ReplyCreateApiTest.java
> 댓글 한 개 조회 API
- closed #421 
답글 작성창에 본인 프로필 이미지도 포함되어 있어서 넣어줬습니다!
=> 댓글 한 개 조회 API

src/main/resources/db/migration/V3.5__add_unique_index_on_kakaoId.sql
> 카카오 id 유니크 제약 조건 추가
- closed #440
=> 카카오 id 유니크 제약 조건 추가

src/main/resources/static/css/diary/write-page.css, src/main/resources/templates/diary/write-page.html
> 일기 작성페이지 툴팁, 도움말 버그 수정
- closed #442
=> 일기 작성페이지 툴팁, 도움말 버그 수정

src/main/java/com/exchangediary/comment/service/CommentService.java, src/main/java/com/exchangediary/comment/ui/dto/response/CommentCreateResponse.java
> 댓글 등록 API 응답 수정
- closed #454
=> 댓글 등록 API 응답 수정

src/test/java/com/exchangediary/comment/api/CommentCreateApiTest.java
> 댓글 등록 API 응답 수정 후 테스트 실패 수정
- closed #458 
앞으로 테스트를 잘 돌리겠습니다🥲
=> 댓글 등록 API 응답 수정 후 테스트 실패 수정

src/main/java/com/exchangediary/member/service/AnonymousService.java
> 익명 조회 API 오류 해결
- 배포 후, 시작 페이지가 두 번 로딩되는 문제가 발생하였습니다. 
- 익명 조회 API에서 access token 만료 시, 만료된 토큰으로부터 사용자 id를 찾아오는 문제였고, 코드 수정했습니다.
- closed #480
=> 익명 조회 API 오류 해결

src/main/resources/static/css/diary/write-page.css, src/main/resources/static/css/group/group-menu.css, src/main/resources/static/js/common/base.js, src/main/resources/static/js/diary/write-page/check-textarea-android.js, src/main/resources/static/js/diary/write-page/check-textarea-ios.js, src/main/resources/static/js/diary/write-page/check-textarea.js, src/main/resources/static/js/group/group-menu.js, src/main/resources/static/js/group/monthly/draw-monthly.js, src/main/resources/templates/group/group-monthly.html
> v1.2 배포 후 발견된 버그들을 핫픽스했습니다.
- closed #495 
자세한 내용은 #495 를 참고해주세요.
지피티야 고마워
=> v1.2 배포 후 발견된 버그 수정
